apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    {{- include "jtl-reporter.labels" (dict "component" "db" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - name: "{{ .Values.db.service.port }}"
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
  selector:
    {{- include "jtl-reporter.componentSelectorLabels" (dict "component" "db" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
