apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "listener.fullname" . }}
  labels:
    {{- include "jtl-reporter.labels" (dict "component" "listener" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jtl-reporter.componentSelectorLabels" (dict "component" "listener" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jtl-reporter.componentSelectorLabels" (dict "component" "listener" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jtl-reporter.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: listener
          image: "{{ .Values.listener.image.repository }}:{{ .Values.listener.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.listener.service.port }}
              protocol: TCP
          livenessProbe:
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            exec:
              command:
                - pgrep
                - node
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            exec:
              command:
                - pgrep
                - node
          startupProbe:
            initialDelaySeconds: 10
            failureThreshold: 14
            periodSeconds: 5
            exec:
              command:
                - pgrep
                - node
          env:
            - name: DB_HOST
              value: db
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: jtlreporter_token
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
