apiVersion: v1
kind: Service
metadata:
  name: listener
  labels:
    {{- include "jtl-reporter.labels" (dict "component" "listener" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
spec:
  type: {{ .Values.listener.service.type }}
  ports:
    - name: "{{ .Values.listener.service.port }}"
      type: {{ .Values.listener.service.type }}
      port: {{ .Values.listener.service.port }}
      targetPort: {{ .Values.listener.service.port }}
  selector:
    {{- include "jtl-reporter.componentSelectorLabels" (dict "component" "listener" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
